swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /transactions:
    get:
      tags:
        - Transaction Module
      summary: Get all transactions
      description: API for retrieving all transactions, grouped by account.
      security:
        - Bearer: []
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid request
        '401':
          description: Authorization information is missing or invalid
        '500':
          description: Internal Server Error
  /transactions/month/{month}:
    get:
      tags:
        - Transaction Module
      summary: Get all transactions for a specific month
      description: API for retrieving all transactions for a specific month, grouped by account.
      security:
        - Bearer: []
      parameters:
        - in: path
          name: month
          description: The month for which to retrieve transactions (in the format YYYY-MM)
          required: true
          type: string
      responses:
        '200':
          description: Transactions retrieved successfully for the given month
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid request
        '401':
          description: Authorization information is missing or invalid
        '500':
          description: Internal Server Error
  /transactions/{id}/:
    get:
      tags:
        - Transaction Module
      summary: Get a specific transaction
      description: API for retrieving the details of a specific transaction.
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: ID of the transaction to retrieve
          required: true
          type: string
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '401':
          description: Authorization information is missing or invalid
        '400':
          description: Invalid request
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transaction Module
      summary: Update a specific transaction
      description: API for updating certain information of a specific transaction, such as the amount or date.
       The transaction itself cannot be added or deleted.
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: New information for the transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200':
          description: Transaction updated successfully
        '400':
          description: Invalid request
        '401':
          description: Authorization information is missing or invalid
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
definitions:
  TransactionsResponse:
    type: object 
    properties:
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  TransactionResponse:
    type: object 
    properties:
      transaction:
        $ref: '#/definitions/Transaction'
  TransactionUpdate:
    type: object 
    properties:
      title:
        type : string 
        description : The new title of the transaction.
      amount :
         type : number 
         description : The new amount of the transaction.
      date :
         type : string 
         format: date-time 
         description : The new date of the transaction.
  Transaction :
    type : object 
    properties :
       title :
         type : string 
         description : The title of the transaction.
       amount :
         type : number 
         description : The amount of the transaction.
       date :
         type : string 
         format: date-time 
         description : The date of the transaction.
