swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
  paths:

  
  # Endpoint pour récupérer toutes les transactions
  /transactions:
    get:
      tags:
        - Transaction Module
      summary: Get all transactions
      description: API for retrieving all transactions, grouped by account.
      # Nécessite un token d'autorisation dans l'en-tête de la requête
      security:
        - Bearer: []
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid request
        '401':
          description: Authorization information is missing or invalid
        '500':
          description: Internal Server Error


# 2- Endpoint pour récupérer toutes les transactions pour un mois donné
/transactions/month/{month}:
  get:
    tags:
      - Transaction Module
    summary: Get all transactions for a specific month
    description: API for retrieving all transactions for a specific month, grouped by account.
    # Nécessite un token d'autorisation dans l'en-tête de la requête
    security:
      - Bearer: []
    parameters:
      - in: path
        name: month
        description: The month for which to retrieve transactions (in the format YYYY-MM)
        required: true
        type: string
    responses:
      '200':
        description: Transactions retrieved successfully for the given month
        schema:
          $ref: '#/definitions/TransactionsResponse'
      '400':
        description: Invalid request
      '401':
          description: Authorization information is missing or invalid
      '500':
        description: Internal Server Error



  # 3- Endpoint pour récupérer une transaction spécifique
  # GET
  /transactions/{id}/:
    get:
      tags:
        - Transaction Module
      summary: Get a specific transaction
      description: API for retrieving the details of a specific transaction.
      # Nécessite un token d'autorisation et l'ID de la transaction en tant que paramètre de chemin
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: ID of the transaction to retrieve
          required: true
          type: string
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '401':
          description: Authorization information is missing or invalid
        '400':
          description: Invalid request
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

    # Endpoint pour mettre à jour une transaction spécifique
    # PUT
    put:
      tags:
        - Transaction Module
      summary: Update a specific transaction
      description: API for updating certain information of a specific transaction, such as the amount or date.
       The transaction itself cannot be added or deleted.
      # Nécessite un token d'autorisation, l'ID de la transaction en tant que paramètre de chemin, 
      # et les nouvelles informations de la transaction en tant que corps de la requête.
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: New information for the transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200':
          description: Transaction updated successfully
        '400':
          description: Invalid request
        '401':
          description: Authorization information is missing or invalid
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error


# Section définitions
      definitions:
      # La réponse de l'API quand on demande toutes les transactions
  TransactionsResponse:
    type: object 
    properties:
     # Un tableau de transactions
      transactions:
        type: array
         # Chaque élément du tableau est une Transaction
        items:
          $ref: '#/definitions/Transaction'
            # La réponse de l'API quand on demande une transaction spécifique
  TransactionResponse:
    type: object 
    properties:
       # La transaction demandée
      transaction:
        $ref: '#/definitions/Transaction'
        # Les informations à fournir à l'API pour mettre à jour une transaction
  TransactionUpdate:
    type: object 
    properties:
       # Le nouveau titre de la transaction
      title:
        type : string 
        description : The new title of the transaction.
         # Le nouveau montant de la transaction
      amount :
         type : number 
         description : The new amount of the transaction.
            # La nouvelle date de la transaction
       date :
         type : string 
         format: date-time 
         description : The new date of the transaction.
         
           # La structure d'une transaction
  Transaction :
    type : object 
    properties :
       # Le titre de la transaction
       title :
         type : string 
         description : The title of the transaction.
          # Le montant de la transaction
       amount :
         type : number 
         description : The amount of the transaction.
         # La date de la transaction
       date :
         type : string 
         format:date-time 
         description : The date of the transaction.
